### PR TITLE
Linting fixes

### PR DESCRIPTION
**Pull request by mfitz**
Fixes 88 Flake8 linting errors that appeared when I made the linting check use the full rule set.

#### Before

```bash
$ ./scripts/lint-check.sh

...
2     E122 continuation line missing indentation or outdented
1     E125 continuation line with same indent as next logical line
1     E128 continuation line under-indented for visual indent
1     E211 whitespace before '('
4     E231 missing whitespace after ','
44    E251 unexpected spaces around keyword / parameter equals
3     E302 expected 2 blank lines, found 1
2     E303 too many blank lines (2)
1     E304 blank lines found after function decorator
1     E306 expected 1 blank line before a nested definition, found 0
2     E501 line too long (132 > 120 characters)
1     E502 the backslash is redundant between brackets
9     F401 'json' imported but unused
6     F541 f-string is missing placeholders
1     F811 redefinition of unused 'config' from line 14
5     W291 trailing whitespace
4     W293 blank line contains whitespace
88
```

#### After
```bash
$ ./scripts/lint-check.sh
~/workspace/osmox ~/workspace/osmox

0
~/workspace/osmox
✔ The code is as clean as a baby's bottom! ✔
```

I have also slightly downgraded the patch version of the `osmium` dependency. The original version (`3.1.3`) does not work on my old Mac OS (10.13.6), giving fatal errors when running both the tool itself and the unit tests:

```bash
$ osmox --help

Traceback (most recent call last):
  File "/Users/mickyfitz/.pyenv/versions/osmox-3.7.6/bin/osmox", line 11, in <module>
    load_entry_point('osmox', 'console_scripts', 'osmox')()
  File "/Users/mickyfitz/.pyenv/versions/3.7.6/envs/osmox-3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/mickyfitz/.pyenv/versions/3.7.6/envs/osmox-3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/mickyfitz/.pyenv/versions/3.7.6/envs/osmox-3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/mickyfitz/.pyenv/versions/3.7.6/envs/osmox-3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/mickyfitz/workspace/osmox/osmox/main.py", line 7, in <module>
    from osmox.helpers import PathPath
  File "/Users/mickyfitz/workspace/osmox/osmox/helpers.py", line 6, in <module>
    from osmox import build
  File "/Users/mickyfitz/workspace/osmox/osmox/build.py", line 5, in <module>
    import osmium
  File "/Users/mickyfitz/.pyenv/versions/3.7.6/envs/osmox-3.7.6/lib/python3.7/site-packages/osmium/__init__.py", line 1, in <module>
    from osmium._osmium import *
ImportError: dlopen(/Users/mickyfitz/.pyenv/versions/3.7.6/envs/osmox-3.7.6/lib/python3.7/site-packages/osmium/_osmium.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/mickyfitz/.pyenv/versions/3.7.6/envs/osmox-3.7.6/lib/python3.7/site-packages/osmium/.dylibs/liblz4.1.9.3.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/mickyfitz/.pyenv/versions/3.7.6/envs/osmox-3.7.6/lib/python3.7/site-packages/osmium/.dylibs/liblz4.1.9.3.dylib

```

```bash
$ ./scripts/code-coverage.sh

=========================================================================== ERRORS ===========================================================================
_______________________________________________________ ERROR collecting tests/test_activityhandler.py _______________________________________________________
ImportError while importing test module '/Users/mickyfitz/workspace/osmox/tests/test_activityhandler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/osmox-3.7.6/lib/python3.7/site-packages/_pytest/python.py:578: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
../../.pyenv/versions/osmox-3.7.6/lib/python3.7/site-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
../../.pyenv/versions/3.7.6/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:677: in _load_unlocked
    ???
../../.pyenv/versions/osmox-3.7.6/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
tests/test_activityhandler.py:6: in <module>
    from osmox import config, build, helpers
osmox/config.py:4: in <module>
    from osmox import build
osmox/build.py:5: in <module>
    import osmium
../../.pyenv/versions/osmox-3.7.6/lib/python3.7/site-packages/osmium/__init__.py:1: in <module>
    from osmium._osmium import *
E   ImportError: dlopen(/Users/mickyfitz/.pyenv/versions/osmox-3.7.6/lib/python3.7/site-packages/osmium/_osmium.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
E     Referenced from: /Users/mickyfitz/.pyenv/versions/osmox-3.7.6/lib/python3.7/site-packages/osmium/.dylibs/liblz4.1.9.3.dylib (which was built for Mac OS X 10.15)
E     Expected in: /usr/lib/libSystem.B.dylib
E    in /Users/mickyfitz/.pyenv/versions/osmox-3.7.6/lib/python3.7/site-packages/osmium/.dylibs/liblz4.1.9.3.dylib
```

Downgrading to the latest version of `osmium` before the [upgraded libosmium dependency](https://github.com/osmcode/pyosmium/blob/master/CHANGELOG.md#311---2021-01-12) (`3.1.0`) fixes this without breaking the CI build, but somebody on a later version of the OS - which I think is probably pretty much everyone 🤪 - should confirm that we have not lost anything with this slight downgrade.

I also found that `scripts/code-coverage.sh` was not executable on my machine - we've seen this before with script that were originally created using WSL, I think.

All changes are linting fixes unless otherwise commented.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,3 +1,134 @@
+# Byte-compiled / optimized / DLL files
```
Comment (mfitz) [inline .gitignore:1]: Added standard python `.gitignore` things

File: requirements.txt [hunk 2]
```diff
@@ -1,11 +1,12 @@
+Click==7.1.2
```
Comment (mfitz) [inline requirements.txt:1]: Since I was editing this file, I also organised the dependencies into alphabetical order for readability.

File: requirements.txt [hunk 3]
```diff
@@ -1,11 +1,12 @@
...
+flake8==3.9.2
+geopandas==0.9.0
+osmium==3.1.0
 pandas==1.2.4
-osmium==3.1.3
+pyproj==3.1.0
```
Comment (mfitz) [inline requirements.txt:6]: The latest version that works out-of-the-box on the old Mac OS. Probably only affects me in the team, but given this is a public repo, who knows? I will probably be off this OS next month, BTW.

File: requirements.txt [hunk 4]
```diff
@@ -1,11 +1,12 @@
+Click==7.1.2
+flake8==3.9.2
+geopandas==0.9.0
```
Comment (mfitz) [inline requirements.txt:3]: Geopandas version was not pinned - was this deliberate?

File: scripts/lint-check.sh [hunk 5]
```diff
@@ -0,0 +1,27 @@
+#!/usr/bin/env bash
```
Comment (mfitz) [inline scripts/lint-check.sh:1]: We should make a git commit hook that uses this.

File: requirements.txt (hunk 2 above)
Comment (fredshone) [reply requirements.txt:1]: 💌

File: requirements.txt (hunk 4 above)
Comment (fredshone) [reply requirements.txt:3]: no - thanks

File: requirements.txt (hunk 3 above)
Comment (fredshone) [reply requirements.txt:6]: 👍🏻

**Review by fredshone — APPROVED** [review]
thanks so much!
